language: python

python:
- "3.5"

before_install:
- rvm install 2.2.3

install:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- pip install git+git://github.com/citruspi/ljon.git
- pip install jinja2-highlight
- pip install click
- pip install pillow
- pip install watchdog

script: return 0

before_deploy: make release

deploy:
  provider: s3
  access_key_id: AKIAIKAOQMWIKVZMP4BQ
  secret_access_key:
    secure: QEbXthgBIGTZS40Xeg7Zv4/YOfD6Klnuaf8OYwMvS54zKabdvTZm/nR4hbJwrkWNOsY1Vm3uKAzCt+sS4j4Z8eBzTBJ9lBMFKeudgik9SBbNobElRSU6UkLqjC0W+d7CsPVmV8/9WG4TsdbXo3EI2V41Z4L2USG6MOdu7rbgOcA=
  bucket: io.citruspi.www
  skip_cleanup: true
  local-dir: release
  acl: public_read
  on:
    all_branches: true
    repo: citruspi/citruspi.io
