# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title/

# Setup
title:            citruspi
tagline:          ''
description:      ''
url:              http://citruspi.io

author:
  name:           'citruspi'
  url:            http://citruspi.io

paginate:         100

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/citruspi/citruspi.io
