---
metadata:
  title: "citruspi"
ignore:
- ".*\\..+\\.j2.json"
- ".*\\..+\\.j2.yaml"
- "\\./public.*"
- ".*/static/images/stream-[a-z]\\.+"
- ".*/static/images/collection-[a-z]\\.+"
processors:
  "(.*\\..+)\\.j2":
    processor: jinja
  "(.*/static/images/stream-.+)":
    processor: pillow
    pipeline:
    - func: resize
      width: 500
    - func: write
      name: "{public_path}/{path}/{name}.{extension}"
  "(.*/static/images/collection-.+)":
    processor: pillow
    pipeline:
    - func: resize
      width: 500
    - func: write
      name: "{public_path}/{path}/{name}.{extension}"
  "(.*/static/images/photography/.*/.+\\.jpg)":
    copy: true
    processor: pillow
    pipeline:
    - func: write
      name: "{public_path}/{path}/{name}-web.{extension}"

